### ISSUE TITLE
Location of css for tailwind

### ISSUE THREAD

**Issue by knownasilya** [NullVoxPopuli/ember-apply#11]
I get that the tailwind instructions say to put it into the main page, but I think they aren't thinking of long running and bigger projects. It adds to the clutter already in the root folder and you don't expect css to be there in an ember app.

I'd put it into app/styles or vendor folders.

**Comment by NullVoxPopuli** [comment]
yeah that's fair.
`app/styles` is problematic because ember-cli's style pipeline has control ever that (and ember-cli controls all of `app`).

:thinking: 

Thoughts of maybe adding a top-level `tailwind` folder to place everything? that way it's one additional thing, rather than 3+?

**Comment by NullVoxPopuli** [comment]
oh that could work!

**Comment by NullVoxPopuli** [comment]
wip: https://github.com/NullVoxPopuli/ember-apply/pull/12

**Comment by NullVoxPopuli** [comment]
Coming up
