### ISSUE TITLE
Is there a way to run`ember-apply tailwind` on an Ember addon('s dummy app)?

### ISSUE THREAD

**Issue by jacobq** [NullVoxPopuli/ember-apply#270]
I was thinking of using the `dummy` app of an ember addon as a "live demo" (and maybe deploy on GitHub pages) so was going to spruce the appearance of it up a bit with tailwind. However, it looks like the base folder needs to have both `package.json` (would be in repo root) and `app/index.html` (would be in `tests/dummy`). 

https://github.com/NullVoxPopuli/ember-apply/blob/f7cd8aaa499751ccba512fdcef19145794881522/packages/ember/tailwind/index.js#L18-L26

**Comment by NullVoxPopuli** [comment]
yeah, idk how much I want to support addon's dummy apps :thinking: 

The main thing is that v2 addons have decent support for most things, and v2 addons use normal apps for their tests / docs -- and it's all-around much easier to support those

**Comment by jacobq** [comment]
Oh, cool, sounds like this use case won't matter in the future then. I was mostly curious, and it sounds like the answer, "This isn't supported."
