### ISSUE TITLE
ember-apply tailwind does not modify ember-cli-build

### ISSUE THREAD

**Issue by mcfiredrill** [NullVoxPopuli/ember-apply#459]
Not sure if this was intended to be part of the feature or not, but I believe ember-cli-build.js needs to be modified for tailwind to be part of the build process.
https://tailwindcss.com/docs/guides/emberjs

**Comment by NullVoxPopuli** [comment]
Not with the technique this code mod implements -- This codemod doesn't integrate with webpack and only outputs a public asset.

Both approaches are valid, but different
