### ISSUE TITLE
Using official Tailwind guides for ember?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-apply#491]
Just noticed that Tailwind has [official documentation for EmberJS](https://tailwindcss.com/docs/guides/emberjs). Would it make sense to update the script for tailwind here to match?

One thing that I noticed is that it somehow hooks things together so it's not necessary to spawn the `pnpm run tailwind:watch` in separate terminal. Which is nice.

**Comment by NullVoxPopuli** [comment]
I think it's worth a separate tailwind implementation, maybe called `tailwind-webpack`.

I think there is still a lot of value in using the simpler tailwind-CLI approach because it can survive packager-changes (webpack vs vite vs broccoli, etc).
