### ISSUE TITLE
`npx ember-apply typescript` doesn't work in v1 addons

### ISSUE THREAD

**Issue by Windvis** [NullVoxPopuli/ember-apply#527]
The documentation mentions that this automation should also work for v1 addons, but when I try it on [this one](https://github.com/appuniversum/ember-appuniversum) I see the following console output:

```
Debugger attached.
ℹ Downloading from npm...
ℹ Applying: typescript
ℹ If there are any bugs with this applyable, feel free to report at https://github.com/NullVoxPopuli/ember-apply/issues
Could not determine where to enable TypeScripts in ember-cli-build.js. Please refer to the docs: https://github.com/emberjs/ember-cli-babel#enabling-typescript-transpilation
✖ ENOENT: no such file or directory, open 'types/global.d.ts'
[Error: ENOENT: no such file or directory, open 'types/global.d.ts'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'types/global.d.ts'
}
```

My guess is that [this check](https://github.com/NullVoxPopuli/ember-apply/blob/12bf18a045fcc05b43033fc485c84a6cf1c4c4c0/packages/ember/typescript/src/ensure-ts-transpilation.js#L9) fails because the ember-cli-build.js file for addons seems to contain [`const EmberAddon = require('ember-cli/lib/broccoli/ember-addon');`](https://github.com/ember-cli/ember-cli/blob/f824a6aee6e804fe4584fb037e893e3bbf93370a/blueprints/addon/files/ember-cli-build.js#L3) instead of what that check looks for.

**Comment by NullVoxPopuli** [comment]
thanks for reporting!!!
